name: Upload build asset

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload build asset for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            buildCmd: env GOOS=linux GOARCH=amd64 go build -o zcli-linux-amd64 ./main.go && tar -czvf zcli-linux-amd64.tar.gz zcli-linux-amd64
            file: zcli-linux-amd64
            args:
            strip: true
          - os: ubuntu-latest
            buildCmd: env GOOS=linux GOARCH=386 go build -o zcli-linux-i386 ./main.go && tar -czvf zcli-linux-i386.tar.gz zcli-linux-i386
            file: zcli-linux-i386
            args:
            strip: true
          - os: macos-latest
            buildCmd: env GOOS=darwin GOARCH=amd64 go build -o zcli-darwin-amd64 ./main.go && tar -czvf zcli-darwin-amd64.tar.gz zcli-darwin-amd64
            file: zcli-darwin-amd64
            args:
            strip: false

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          export GOPATH=$HOME/go
          ./tools/install.sh

      - name: Build
        run: ${{ matrix.buildCmd }}

      - name: Compress binary
        uses: svenstaro/upx-action@v1-release
        with:
          file: ./${{ matrix.file }}
          args: ${{ matrix.args }}
          strip: ${{ matrix.strip }}

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.file }}
          asset_name: ${{ matrix.file }}
          asset_content_type: application/octet-stream

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci --ignore-scripts
      - run: npm i -g replace-in-files-cli
      - run: replace-in-files --string='v0.0.0-zerops' --replacement='${{ github.event.release.tag_name }}' package.json
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
